// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stockbitpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImdbServiceClient is the client API for ImdbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImdbServiceClient interface {
	Movies(ctx context.Context, in *RequestBody, opts ...grpc.CallOption) (*ResponseBody, error)
	Movie(ctx context.Context, in *RequestBody, opts ...grpc.CallOption) (*ResponseBody, error)
}

type imdbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImdbServiceClient(cc grpc.ClientConnInterface) ImdbServiceClient {
	return &imdbServiceClient{cc}
}

func (c *imdbServiceClient) Movies(ctx context.Context, in *RequestBody, opts ...grpc.CallOption) (*ResponseBody, error) {
	out := new(ResponseBody)
	err := c.cc.Invoke(ctx, "/stockbit.ImdbService/Movies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imdbServiceClient) Movie(ctx context.Context, in *RequestBody, opts ...grpc.CallOption) (*ResponseBody, error) {
	out := new(ResponseBody)
	err := c.cc.Invoke(ctx, "/stockbit.ImdbService/Movie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImdbServiceServer is the server API for ImdbService service.
// All implementations must embed UnimplementedImdbServiceServer
// for forward compatibility
type ImdbServiceServer interface {
	Movies(context.Context, *RequestBody) (*ResponseBody, error)
	Movie(context.Context, *RequestBody) (*ResponseBody, error)
	mustEmbedUnimplementedImdbServiceServer()
}

// UnimplementedImdbServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImdbServiceServer struct {
}

func (UnimplementedImdbServiceServer) Movies(context.Context, *RequestBody) (*ResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Movies not implemented")
}
func (UnimplementedImdbServiceServer) Movie(context.Context, *RequestBody) (*ResponseBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Movie not implemented")
}
func (UnimplementedImdbServiceServer) mustEmbedUnimplementedImdbServiceServer() {}

// UnsafeImdbServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImdbServiceServer will
// result in compilation errors.
type UnsafeImdbServiceServer interface {
	mustEmbedUnimplementedImdbServiceServer()
}

func RegisterImdbServiceServer(s grpc.ServiceRegistrar, srv ImdbServiceServer) {
	s.RegisterService(&ImdbService_ServiceDesc, srv)
}

func _ImdbService_Movies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImdbServiceServer).Movies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stockbit.ImdbService/Movies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImdbServiceServer).Movies(ctx, req.(*RequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImdbService_Movie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImdbServiceServer).Movie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stockbit.ImdbService/Movie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImdbServiceServer).Movie(ctx, req.(*RequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

// ImdbService_ServiceDesc is the grpc.ServiceDesc for ImdbService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImdbService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stockbit.ImdbService",
	HandlerType: (*ImdbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Movies",
			Handler:    _ImdbService_Movies_Handler,
		},
		{
			MethodName: "Movie",
			Handler:    _ImdbService_Movie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stockbitpb.proto",
}
